# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"firefox" = ""
"librewolf" = ""
"freetube" = ""
"ranger" = ""
"nautilus" = ""
"file manager" = ""
"libreoffice calc" = ""
"libreoffice writer" = "󰏪"
"nvim" = ""
"netflix" = "󰝆"
"lutris" = "󱎓"
"bluetooth" = ""
"xournalpp" = ""
"obsidian" = "󰊄"
"gthumb" = ""
"menu" = "󰮫"
"melonds" = "󰟡"
"calculator" = "󰪚"
"transmission" = ""
"videostream" = "󰑋"
"disk usage" = "󰨣"
".pdf" = ""
"github" = ""
"signal" = "󰚢"
"texstudio" = "󰴑"
"boxes" = "󰒔"
"todoist" = ""
"alacritty" = " "
"discord" = "󰙯"

[other]
fallback_icon = "󰢤"
deduplicate_icons = false
#separator = ": "
