#!/bin/bash

if [[ $(whoami) != "root" ]]
then
    echo "Il faut être root"
    exit 1
fi

#grub-btrfs

packages="
neovim
alacritty
evince
nautilus
gnome-calculator
ranger
xournalpp
fzf
acpi
feh
glances
waylock
ripgrep
rofi
waybar
wl-mirror
dunst
gnome-disk-utility
mpd
mpc
fastfetch
pass
libffi
python-cffi
python-matplotlib
python-pynvim
grim
python-pip
rsync
zsh
zenity
util-linux
python-certifi
cronie
network-manager-applet
blueman
libinput
discord
sddm
wtype
starship
ufw
wget
libreoffice-still
libnotify
vim
wl-clipboard
man-db
man-pages
texinfo
reflector
btrfs-progs
ttf-liberation
noto-fonts-emoji
adobe-source-code-pro-fonts
otf-font-awesome
ttf-droid
ntfs-3g
p7zip
xdg-utils
gstreamer
gst-plugins-bad
gst-plugins-base
gst-plugins-ugly
gst-plugin-pipewire
gstreamer-vaapi
gst-plugins-good
gst-libav
gstreamer-vaapi
intel-ucode
intel-media-driver
intel-gmmlib
bluez
bluez-utils
bluez-plugins
ghostscript
gsfonts
cups
cups-filters
cups-pdf
system-config-printer
avahi
foomatic-db-engine
foomatic-db
foomatic-db-ppds
foomatic-db-nonfree
foomatic-db-nonfree-ppds
foomatic-db-gutenprint-ppds
gutenprint
a52dec
faac
faad2
flac
jasper
lame
libdca
libdv
libmad
libmpeg2
libtheora
libvorbis
libxv
wavpack
x264
xvidcore
"

for package in $packages
do
    pacman -S --needed --noconfirm $package &> /dev/null

    if [[ "$?" == "0" ]]
    then
        echo -e "\033[32mOK\033[0m $package"
    else
        echo -e "\033[31mERREUR\033[0m $package"
    fi
done

