#!/bin/bash

if [[ $(whoami) != "root" ]]
then
    echo "Il faut être root"
    exit 1
fi

# Paquets potentiellement utiles pour les polices et dictionnaires 
#sudo pacman -S enchant mythes-en ttf-liberation hunspell-en_US ttf-bitstream-vera pkgstats adobe-source-sans-pro-fonts gst-plugins-good ttf-droid ttf-dejavu aspell-en icedtea-web gst-libav ttf-ubuntu-font-family ttf-anonymous-pro jre8-openjdk languagetool libmythes 

packages="
neovim
alacritty
evince
ranger
xournalpp
fzf
acpi
feh
glances
git
ripgrep
light
rofi
waybar
mpd
mpc
libffi
python3-devel
python-cffi
grim
swappy
flatpak
python-pip
zsh
util-linux
python-certifi
cronie
network-manager-applet
blueman
libinput
discord
sddm
wtype
starship
ufw
btrfs-progs
vim
man-db
man-pages
texinfo
reflector
btrfs-progs
btrfs-assistant
ttf-liberation
noto-fonts-emoji
adobe-source-code-pro-fonts
otf-font-awesome
ttf-droid
ntfs-3g
p7zip
xdg-utils
downgrade
gstreamer
gst-plugins-bad
gst-plugins-base
gst-plugins-ugly
gst-plugin-pipewire
gstreamer-vaapi
gst-plugins-good
gst-libav
gstreamer-vaapi
intel-ucode
intel-media-driver
intel-gmmlib
bluez
bluez-utils
bluez-plugins
ghostscript
gsfonts
cups
cups-filters
cups-pdf
system-config-printer
avahi
foomatic-db-engine
foomatic-db
foomatic-db-ppds
foomatic-db-nonfree
foomatic-db-nonfree-ppds
foomatic-db-gutenprint-ppds
gutenprint
a52dec
faac
faad2
flac
jasper
lame
libdca
libdv
libmad
libmpeg2
libtheora
libvorbis
libxv
wavpack
x264
xvidcore
gstreamer0.10-plugins
"

packages_aur="
wlsunset
signal-desktop-beta
librewolf
melonds
texstudio-git
flashfocus
fusuma
swayfx
btrfs-assistant
pacman-contrib
arc-gtk-theme
"

packages_flatpak="
"

packages_pip="
pynvim
"

#swaylock-effects
#waylock

check_install()
{
    if [[ "$1" == "0" ]]
    then
        echo "OK $package"
    else
        echo "ERREUR $package"
    fi
}

for package in $packages
do
    pacman -S --needed --noconfirm $package 2>&1 > /dev/null
    check_install $? $package
done

for package in $packages_aur
do
    yay -S --noconfirm $package 2>&1 > /dev/null
    check_install $? $package
done

for package in $packages_flatpak
do
    flatpak install $package 2>&1 > /dev/null
    check_install $? $package
done

for package in $packages_pip
do
    pip install $package 2>&1 > /dev/null
    check_install $? $package
done

