#!/bin/bash

if [[ $(whoami) != "root" ]]
then
    echo "Il faut être root"
    exit 1
fi

# Paquets potentiellement utiles pour les polices et dictionnaires 
#sudo pacman -S enchant mythes-en ttf-liberation hunspell-en_US ttf-bitstream-vera pkgstats adobe-source-sans-pro-fonts gst-plugins-good ttf-droid ttf-dejavu aspell-en icedtea-web gst-libav ttf-ubuntu-font-family ttf-anonymous-pro jre8-openjdk languagetool libmythes 

packages="
neovim
alacritty
evince
nautilus
ranger
xournalpp
fzf
acpi
feh
glances
ripgrep
light
rofi
waybar
dunst
mpd
mpc
libffi
python-cffi
python-matplotlib
python-pynvim
grim
swappy
python-pip
rsync
grub-btrfs
zsh
util-linux
python-certifi
cronie
network-manager-applet
blueman
libinput
ruby
discord
sddm
wtype
starship
ufw
wget
lutris
libnotify
vim
wl-clipboard
man-db
man-pages
texinfo
reflector
btrfs-progs
ttf-liberation
noto-fonts-emoji
adobe-source-code-pro-fonts
otf-font-awesome
ttf-droid
ntfs-3g
p7zip
xdg-utils
gstreamer
gst-plugins-bad
gst-plugins-base
gst-plugins-ugly
gst-plugin-pipewire
gstreamer-vaapi
gst-plugins-good
gst-libav
gstreamer-vaapi
intel-ucode
intel-media-driver
intel-gmmlib
bluez
bluez-utils
bluez-plugins
ghostscript
gsfonts
cups
cups-filters
cups-pdf
system-config-printer
avahi
foomatic-db-engine
foomatic-db
foomatic-db-ppds
foomatic-db-nonfree
foomatic-db-nonfree-ppds
foomatic-db-gutenprint-ppds
gutenprint
a52dec
faac
faad2
flac
jasper
lame
libdca
libdv
libmad
libmpeg2
libtheora
libvorbis
libxv
wavpack
x264
xvidcore
gstreamer0.10-plugins
"

#swaylock-effects
#waylock

for package in $packages
do
    pacman -S --needed --noconfirm $package &> /dev/null

    if [[ "$1" == "0" ]]
    then
        echo -e "\033[32mOK\033[0m $package"
    else
        echo -e "\033[31mERREUR\033[0m $package"
    fi
done

