#!/bin/bash

declare -a configs=(
    "alacritty"
    "dunst"
    "flashfocus"
    "nvim"
    "ranger"
    "rofi"
    "sway"
    "swaylock"
    "waybar"
    "zathura"
    "fusuma"
    "mpd"
    "workstyle"
    "starship.toml"
    "myzshrc"
)

path2="$HOME/Documents/post_install_arch/myconfig"

if [[ ! -e "$path2" ]]
then
    echo "Le chemin "$path2" n'existe pas!!!"
    exit 2
fi

for config in "${configs[@]}"
do
    path1="$HOME/.config/${config}"

    if [[ ! -e "$path1" ]]
    then
        echo "Le chemin "$path1" n'existe pas!!!"
        exit 1
    fi

    {
        rsync -a --delete --exclude='.cache' "${path1}" "${path2}" &> /dev/null
        echo "${path1} -> ${path2}"
    } &
done

wait

notify-send "Le refresh est terminé!"

