format = """
[░▒▓](fg:#dbd6b7)\                              
[    ](fg:#090c0c bg:#dbd6b7)\                              
[](fg:#dbd6b7 bg:#75D296)\                               
$directory\
[](fg:#75D296 bg:#10ce75)\                               
$git_branch\
$git_status\
$git_metrics\
[](fg:#10ce75 bg:#10ce75)\                             
[ ](fg:#10ce75)\                             
"""

right_format = """
[](fg:#75D296)\                             
$time\
$cmd_duration\
$character\
[▓▒░](fg:#75D296)\                              
"""

add_newline = false

[directory]
home_symbol = " "
truncation_symbol = "…/"
truncate_to_repo = false
read_only = "󰒃"
style = "fg:#090c0c bg:#75D296"
format = "[ $path ]($style)[$read_only]($read_only_style)"

[git_branch]
symbol = ""
style = "fg:#090c0c bg:#10ce75"
format = '[ $symbol $branch ]($style)'

[git_status]
untracked = "±"
style = "fg:#090c0c bg:#10ce75"
format = '[($all_status$ahead_behind )]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:#090c0c bg:#75D296"
format = '[$time ]($style)'

[character]
format = "$symbol"
success_symbol = '[ ](fg:#090c0c bg:#75D296)' 
error_symbol = '[ ](fg:#090c0c bg:#75D296)'

[cmd_duration]
style = "fg:#090c0c bg:#75D296"
format = "[$duration]($style)"

