format = """
[░▒▓](fg:#493636)\                                                           
[    ](fg:#f1efef bg:#493636)\                                                           
[](fg:#493636 bg:#8B6C81)\                                                            
$directory\
[](fg:#8B6C81 bg:#cda3cd)\                                                            
$git_branch\
$git_status\
$git_metrics\
[](fg:#cda3cd bg:#cda3cd)\                                                          
[ ](fg:#cda3cd)\                                                          
"""

right_format = """
[](fg:#8B6C81)\                                                          
$time\
$cmd_duration\
$character\
[▓▒░](fg:#8B6C81)\                                                           
"""

add_newline = false

[directory]
home_symbol = " "
truncation_symbol = "…/"
truncate_to_repo = false
read_only = "󰒃"
style = "fg:#f1efef bg:#8B6C81"
format = "[ $path ]($style)[$read_only]($read_only_style)"

[git_branch]
symbol = ""
style = "fg:#f1efef bg:#cda3cd"
format = '[ $symbol $branch ]($style)'

[git_status]
untracked = "±"
style = "fg:#f1efef bg:#cda3cd"
format = '[($all_status$ahead_behind )]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:#f1efef bg:#8B6C81"
format = '[$time ]($style)'

[character]
format = "$symbol"
success_symbol = '[ ](fg:#f1efef bg:#8B6C81)' 
error_symbol = '[ ](fg:#f1efef bg:#8B6C81)'

[cmd_duration]
style = "fg:#f1efef bg:#8B6C81"
format = "[$duration]($style)"

