format = """
[░▒▓](fg:#0d1567)\                                                                                                                 
[    ](fg:#f1efef bg:#0d1567)\                                                                                                                 
[](fg:#0d1567 bg:#3B44A5)\                                                                                                                  
$directory\
[](fg:#3B44A5 bg:#6974e4)\                                                                                                                  
$git_branch\
$git_status\
$git_metrics\
[](fg:#6974e4 bg:#6974e4)\                                                                                                                
[ ](fg:#6974e4)\                                                                                                                
"""

right_format = """
[](fg:#3B44A5)\                                                                                                                
$time\
$cmd_duration\
$character\
[▓▒░](fg:#3B44A5)\                                                                                                                 
"""

add_newline = false

[directory]
home_symbol = " "
truncation_symbol = "…/"
truncate_to_repo = false
read_only = "󰒃"
style = "fg:#f1efef bg:#3B44A5"
format = "[ $path $read_only ]($style)"

[git_branch]
symbol = ""
style = "fg:#f1efef bg:#6974e4"
format = '[ $symbol $branch ]($style)'

[git_status]
untracked = "±"
style = "fg:#f1efef bg:#6974e4"
format = '[($all_status$ahead_behind )]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:#f1efef bg:#3B44A5"
format = '[$time ]($style)'

[character]
format = "$symbol"
success_symbol = '[ ](fg:#f1efef bg:#3B44A5)' 
error_symbol = '[ ](fg:#f1efef bg:#3B44A5)'

[cmd_duration]
style = "fg:#f1efef bg:#3B44A5"
format = "[$duration]($style)"

