format = """
[░▒▓](fg:#e3944e)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
[    ](fg:#090c0c bg:#e3944e)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
[](fg:#e3944e bg:#CC726D)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
$directory\
[](fg:#CC726D bg:#b5518d)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
$git_branch\
$git_status\
$git_metrics\
[](fg:#b5518d bg:#b5518d)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
[ ](fg:#b5518d)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
"""

right_format = """
[](fg:#CC726D)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
$time\
$cmd_duration\
$character\
[▓▒░](fg:#CC726D)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
"""

add_newline = false

[directory]
home_symbol = " "
truncation_symbol = "…/"
truncate_to_repo = false
read_only = "󰒃"
style = "fg:#090c0c bg:#CC726D"
format = "[ $path $read_only ]($style)"

[git_branch]
symbol = ""
style = "fg:#090c0c bg:#b5518d"
format = '[ $symbol $branch ]($style)'

[git_status]
untracked = "±"
style = "fg:#090c0c bg:#b5518d"
format = '[($all_status$ahead_behind )]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:#090c0c bg:#CC726D"
format = '[$time ]($style)'

[character]
format = "$symbol"
success_symbol = '[ ](fg:#090c0c bg:#CC726D)' 
error_symbol = '[ ](fg:#090c0c bg:#CC726D)'

[cmd_duration]
style = "fg:#090c0c bg:#CC726D"
format = "[$duration]($style)"

