format = """
[░▒▓](fg:#2c7a6c)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
[    ](fg:#f1efef bg:#2c7a6c)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
[](fg:#2c7a6c bg:#2D7080)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
$directory\
[](fg:#2D7080 bg:#2f6794)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
$git_branch\
$git_status\
$git_metrics\
[](fg:#2f6794 bg:#2f6794)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
[ ](fg:#2f6794)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
"""

right_format = """
[](fg:#2D7080)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
$time\
$cmd_duration\
$character\
[▓▒░](fg:#2D7080)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
"""

add_newline = false

[directory]
home_symbol = " "
truncation_symbol = "…/"
truncate_to_repo = false
read_only = "󰒃"
style = "fg:#f1efef bg:#2D7080"
format = "[ $path $read_only ]($style)"

[git_branch]
symbol = ""
style = "fg:#f1efef bg:#2f6794"
format = '[ $symbol $branch ]($style)'

[git_status]
untracked = "±"
style = "fg:#f1efef bg:#2f6794"
format = '[($all_status$ahead_behind )]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:#f1efef bg:#2D7080"
format = '[$time ]($style)'

[character]
format = "$symbol"
success_symbol = '[ ](fg:#f1efef bg:#2D7080)' 
error_symbol = '[ ](fg:#f1efef bg:#2D7080)'

[cmd_duration]
style = "fg:#f1efef bg:#2D7080"
format = "[$duration]($style)"

