format = """
[░▒▓](fg:#ed8660)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
[    ](fg:#090c0c bg:#ed8660)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
[](fg:#ed8660 bg:#CA83AD)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
$directory\
[](fg:#CA83AD bg:#a780fa)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
$git_branch\
$git_status\
$git_metrics\
[](fg:#a780fa bg:#a780fa)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
[ ](fg:#a780fa)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
"""

right_format = """
[](fg:#CA83AD)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
$time\
$cmd_duration\
$character\
[▓▒░](fg:#CA83AD)\                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
"""

add_newline = false

[directory]
home_symbol = " "
truncation_symbol = "…/"
truncate_to_repo = false
read_only = "󰒃"
style = "fg:#090c0c bg:#CA83AD"
format = "[ $path $read_only ]($style)"

[git_branch]
symbol = ""
style = "fg:#090c0c bg:#a780fa"
format = '[ $symbol $branch ]($style)'

[git_status]
untracked = "±"
style = "fg:#090c0c bg:#a780fa"
format = '[($all_status$ahead_behind )]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:#090c0c bg:#CA83AD"
format = '[$time ]($style)'

[character]
format = "$symbol"
success_symbol = '[ ](fg:#090c0c bg:#CA83AD)' 
error_symbol = '[ ](fg:#090c0c bg:#CA83AD)'

[cmd_duration]
style = "fg:#090c0c bg:#CA83AD"
format = "[$duration]($style)"

