format = """
[░▒▓](fg:#421446)\                                                                                                                           
[    ](fg:#f1efef bg:#421446)\                                                                                                                           
[](fg:#421446 bg:#2B2246)\                                                                                                                            
$directory\
[](fg:#2B2246 bg:#143046)\                                                                                                                            
$git_branch\
$git_status\
$git_metrics\
[](fg:#143046 bg:#143046)\                                                                                                                          
[ ](fg:#143046)\                                                                                                                          
"""

right_format = """
[](fg:#2B2246)\                                                                                                                          
$time\
$cmd_duration\
$character\
[▓▒░](fg:#2B2246)\                                                                                                                           
"""

add_newline = false

[directory]
home_symbol = " "
truncation_symbol = "…/"
truncate_to_repo = false
read_only = "󰒃"
style = "fg:#f1efef bg:#2B2246"
format = "[ $path $read_only ]($style)"

[git_branch]
symbol = ""
style = "fg:#f1efef bg:#143046"
format = '[ $symbol $branch ]($style)'

[git_status]
untracked = "±"
style = "fg:#f1efef bg:#143046"
format = '[($all_status$ahead_behind )]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:#f1efef bg:#2B2246"
format = '[$time ]($style)'

[character]
format = "$symbol"
success_symbol = '[ ](fg:#f1efef bg:#2B2246)' 
error_symbol = '[ ](fg:#f1efef bg:#2B2246)'

[cmd_duration]
style = "fg:#f1efef bg:#2B2246"
format = "[$duration]($style)"

