format = """
[░▒▓](fg:#2acaea)\                                                                                                                                                                                                                                                                                                                 
[    ](fg:#090c0c bg:#2acaea)\                                                                                                                                                                                                                                                                                                                 
[](fg:#2acaea bg:#15E4B4)\                                                                                                                                                                                                                                                                                                                  
$directory\
[](fg:#15E4B4 bg:#00ff7f)\                                                                                                                                                                                                                                                                                                                  
$git_branch\
$git_status\
$git_metrics\
[](fg:#00ff7f bg:#00ff7f)\                                                                                                                                                                                                                                                                                                                
[ ](fg:#00ff7f)\                                                                                                                                                                                                                                                                                                                
"""

right_format = """
[](fg:#15E4B4)\                                                                                                                                                                                                                                                                                                                
$time\
$cmd_duration\
$character\
[▓▒░](fg:#15E4B4)\                                                                                                                                                                                                                                                                                                                 
"""

add_newline = false

[directory]
home_symbol = " "
truncation_symbol = "…/"
truncate_to_repo = false
read_only = "󰒃"
style = "fg:#090c0c bg:#15E4B4"
format = "[ $path $read_only ]($style)"

[git_branch]
symbol = ""
style = "fg:#090c0c bg:#00ff7f"
format = '[ $symbol $branch ]($style)'

[git_status]
untracked = "±"
style = "fg:#090c0c bg:#00ff7f"
format = '[($all_status$ahead_behind )]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:#090c0c bg:#15E4B4"
format = '[$time ]($style)'

[character]
format = "$symbol"
success_symbol = '[ ](fg:#090c0c bg:#15E4B4)' 
error_symbol = '[ ](fg:#090c0c bg:#15E4B4)'

[cmd_duration]
style = "fg:#090c0c bg:#15E4B4"
format = "[$duration]($style)"

