#!/bin/bash

declare -a folders=(
    "Bureau"
    "Documents"
    "Téléchargements"
    "Musique"
    "Images"
    "Vidéos"
)

read -p "Voulez-vous faire un backup ou une installation $(pwd) [b|i] " res

if [[ "$res" = "b" ]]
then
    read -p "Êtes-vous sûr de vouloir faire le backup dans $(pwd) [y|N] " res

    if [[ "$res" = "y" ]]
    then
        for folder in "${folders[@]}"
        do
            path="${HOME}/${folder}"

            if [[ ! -e "$path" ]]
            then
                echo "\033[31mERREUR\033[0m Le chemin "$path" n'existe pas!!!"
            else
            then
                {
                    sudo rsync -a --delete --exclude='.cache' "${path}" .
                    echo "\033[32mOK\033[0m ${path}"
                } &
            fi
        done

        wait

        notify-send "Le backup est terminé!"
    fi
elif [[ "$res" = "i" ]]
then
    read -p "Êtes-vous sûr de vouloir faire l'installation avec ce dossier
    comme départ $(pwd) [y|N] " res

    if [[ "$res" = "y" ]]
    then
        for folder in "${folders[@]}"
        do
            if [[ ! -e "$folder" ]]
            then
                echo "\033[31mERREUR\033[0m Le chemin "$folder" n'existe pas!!!"
            else
                {
                    sudo rsync -a --delete --exclude='.cache' "${folder}" $HOME
                    echo "\033[32mOK\033[0m ${folder}"
                } &
            fi
        done

        wait

        notify-send "L'installation est terminée!"
    fi
fi

