#!/bin/bash

if [[ $(whoami) != "root" ]]
then
    echo "Il faut être root"
    exit 1
fi

if [[ "$1" = "start" ]]
then
    echo 0 > /sys/module/zswap/parameters/enabled
    swapoff --all
    modprobe zram num_devices=1
    echo zstd > /sys/block/zram0/comp_algorithm
    echo 8G > /sys/block/zram0/disksize
    mkswap --label zram0 /dev/zram0
    swapon --priority 32767 /dev/zram0
elif [[ "$1" = "stop" ]]
then
    swapoff /dev/zram0
    echo 1 > /sys/block/zram0/reset
    modprobe -r zram
fi
